### ISSUE TITLE
Automatic Component Discovery

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#151]
**Is your feature request related to a problem? Please describe.**

Right now, when a new Reader/Transform/Writer is added, it must be explicitly imported into listen.py to be used by the script. Makes it harder and less lightweight to create/incorporate custom components. 

**Describe the solution you'd like**

Would be desirable to specify a custom component path and include all components found along it.

E.g.
```
    listen.py --component_path /my_dir/*.py  \
      --reader MyCustomReader:param1=x,param2=y \
      --transform MyCustomTransform:param1=z \
      --write_logfile /tmp/my_logfile
```
We would need to distinguish between Readers, Transforms and Writers (because of their roles in the pipeline, but that could either be done by relying on a naming convention (ends in 'Reader', etc.) or by the above mechanism, explicitly asserting readerhood. Parameters would be passed in using the ``**kwargs`` mechanism.

The ``component_path`` arg would need to be incorporated into config  definition as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidpablocohn** [comment]
As a first (and probably sufficient) pass, we don't need the listener to be able to find and incorporate arbitrary components from the command line. Should be adequate to do it from a configuration:

```
components:
  - path/to/my/special/components/*.py
  - path/to/another/component/component.py

readers:
  class: TextFileReader
  kwargs:  # initialization kwargs
    file_spec: LICENSE

transforms:
- class: TimestampTransform
- class: MySpecialTransform
  kwargs:
    prefix: "license:"  # enclose in quotes because the ":" can confuse YAML
   
writers:
  class: TextFileWriter
```

Question is how you avoid allowing malicious components to be added. (Or is it? A TextfileReader/TextfileWriter can already read/wipe out any file that the user has access to, so we wouldn't be adding any new security risks...)
