### ISSUE TITLE
SelectFieldsTransform

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#211]
It would be useful (see below) to have a transform that takes a field dict or DASRecord and emits a copy of it that only preserves the specified fields:

```
> select = SelectTransform(keep=['Pitch', 'Heading'])

> record = {'timestamp':1585950398.781196, 'fields':{'Alt':343.4, 'Pitch':-1.32, 'Heading':232.3, 'Roll':3.2}}
> select.transform(record)
{'timestamp':1585950398.781196, 'fields':{'Pitch':-1.32, 'Heading':232.3}}
```
Transform should also support an optional 'delete' arg which if included deletes those fields. The two arguments would be mutually exclusive; if both are present, should we throw an error, or simply give priority to 'keep'?

Should operate correctly on raw dicts (deprecated, but they may still be around - where the field names are the top level keys), field dicts (where the top level dict keys are 'timestamp', 'fields' and possibly others) and DASRecords.

Use cases: we may really only care about a couple of fields from a record that has many fields. This would be an easy way to trim. 

Also: RCRV has some records that need to be split up, with some fields going to one DB table and others going to another.

```
  writers:
  - class: ComposedWriter # writer for writing fields 1 and 2 to table1
    kwargs:
      transforms:
      - class: SelectFieldsTransform
         kwargs:
           keep: ['field_1', field_2']
      writers:
      - class: DatabaseWriter
         kwargs:
           table: 'table1'
 
  - class: ComposedWriter # writer for writing fields 3 and 4 to table2
    kwargs:
      transforms:
      - class: SelectFieldsTransform
         kwargs:
           keep: ['field_3', field_4']
      writers:
      - class: DatabaseWriter
         kwargs:
           table: 'table2'
```
