### ISSUE TITLE
ParseRecord should take single (or list of) parse definitions as argument

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#214]
Rather than relying on a separate set of sensor/sensor_type files, you should be able to specify the string and variables to be extracted as an argument:
```
        - class: ParseTransform
          kwargs:
            metadata_interval: 10
            parse_string: '{datetime:ti},#{temperature:f},{instrument_date},{instrument_time}'
```
