### ISSUE TITLE
RecordParser doesn't capture NMEA message type

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#248]
**Describe the bug**
When the old NMEA parser encountered a record such as 
```
s330 2017-11-04T05:12:19.479303Z $GPZDA,000000.17,07,08,2014,,*78
```
it captured `data_id=s330` and `message_type=INZDA`. The new RecordParser doesn't capture `message_type`, and its current format syntax doesn't support any way to specify what a record's message type is:
```
  format:
    - "$GPGLL,{Latitude:nlat},{NorS:w},{Longitude:nlat},{EorW:w}"
    - "$GPVTG,{CourseTrue:of},T,{CourseMag:of},M,{SpeedKt:of},N,{SpeedKm:of},K"
    - "$GPZDA,{Time:d},{Day:d},{Month:d},{Year:d},{LocalHours:od}"
    - "$GPRMC,{Time:f},{Status:w},{Latitude:nlat},{NorS:w},{Longitude:nlat},{EorW:w},{SpeedKt:f},{Cou
rseTrue:f},{Date:w},{MagneticVar:of},{MagneticVarEorW:ow},{Mode:w}*{Checksum:x}"
```

**Recommendation**
Alter RecordParser to accept an enhanced syntax: instead of just accepting a list of strs, allow it to accept a list of strs or a dict where the key is a message_type str and the values are either strs or lists strs corresponding to formats that match that message type:
```
  format:
    GLL:
    - "$GPGLL,{Latitude:nlat},{NorS:w},{Longitude:nlat},{EorW:w}"
    - "$INGLL,{Latitude:nlat},{NorS:w},{Longitude:nlat},{EorW:w}"
    VTG:
    - "$GPVTG,{CourseTrue:of},T,{CourseMag:of},M,{SpeedKt:of},N,{SpeedKm:of},K"
    - "$INVTG,{CourseTrue:of},T,{CourseMag:of},M,{SpeedKt:of},N,{SpeedKm:of},K"
    ...
```
