### ISSUE TITLE
ValueTransform to allow numerically modifying named values in a DASRecord

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#406]
Take a DASRecord as input and output a modified DASRecord where new derived values have been inserted, e.g.:
```
delete_unmatched: true  # default false - delete all unmatched fields
fields:
  FieldName:
    mult_factor:  1.5   # default 1.0
    add_factor: 3.44  # default 0.0
    output_name: CorrectedFieldName  # default is FieldName
    delete_original: true  # default false; delete original field if transformed field is created
  FieldName2:
    mapping_function: my_magic_function  # God knows how we'd implement this, but...
    output_name: CorrectedFieldName2
    ....
```
