### ISSUE TITLE
ModifyValueTransform factors should be able to be read from files

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#414]
Right now, ModifyValueTransform allows you to tweak values by additive and multiplicative factors, e.g.
```
              FieldName:
                mult_factor:  1.5   # default 1.0
                add_factor: 3.44  # default 0.0
                output_name: CorrectedFieldName  # default is FieldName
                metadata: Field name with linear foobar correction applied
                delete_original: true  # default false
```
When used for calibration/correction factors, it would be desirable to be able to specify that the factors be read from some external YAML file, perhaps even a device definition. Not sure what the syntax for that would look like...
