### ISSUE TITLE
InterpolationTransform hangs when trying to process historical data

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#427]
When InterpolationTransform tries to process old data, it tries to make sure it has processed all the data up to "now" before returning its sequence of snapshots. Because it doesn't know if/when it will be called next. Of course,  when replaying old data, it never reaches "now". 

The following cruise definition triggers the bad behavior:
```
###########################################################
###########################################################
# YAML cruise definition file for OpenRVDAS.
#
# Created by:
#   command:  <<command_line>>
#   time:     <<date_time>> UTC
#   user:     <<user>>
#
###########################################################
cruise:
  id: <<cruise>>
  start: '<<cruise_start>>'
  end: '<<cruise_end>>'

###########################################################


###########################################################
# Global variables - can be overridden by individual loggers
variables:
  cruise: NBP1406
  cruise_start: '2019-07-01'
  cruise_end: '2019-12-31'

  udp_destination: 255.255.255.255
  raw_udp_port: 6224
  parsed_udp_port: 6225

  file_root: /var/tmp/log
  parse_definition_path: test/NBP1406/devices/nbp_devices.yaml

  data_server: localhost:8766
  influx_bucket_name: openrvdas

  command_line: local/usap/create_template_cruise.py test/NBP1406/NBP1406_port_defs.yaml
  date_time: Thu Mar 13 04:38:45 2025
  user: pablo

##############################################
logger_templates:
  #################
  text_file_logger_template:
    configs:
      'off': {}
      net:
        readers:
          class: TextFileReader
          kwargs:
            file_spec: /opt/openrvdas/test/NBP1406/data/<<logger>>/raw/*
            interval: 0.1  #  to avoid computationally crushing the CDS
        transforms:
          class: PrefixTransform
          kwargs:
            prefix: <<logger>>
        writers:
          - class: UDPWriter
            kwargs:
              port: <<raw_udp_port>>
              destination: <<udp_destination>>

  #################
  rebuild_snapshot_template:
    configs:
      'off': { }
      'on':
        readers:
          - class: UDPReader
            kwargs:
              port: <<raw_udp_port>>
        transforms: # Add timestamp and logger label
          - class: ParseTransform
            kwargs:
              metadata_interval: 10
              definition_path: <<parse_definition_path>>
              return_das_record: true
          - class: InterpolationTransform
            kwargs:
              interval: 5
              window: 5
              data_id: snapshot
              metadata_interval: 60  # send metadata every 60 seconds
              field_spec:
                # These fields we do a simple boxcar average on
              - sources: [ KnudDepthHF, KnudDepthLF ]
                algorithm: boxcar_average
                window: 5
                result_prefix: Avg  # Prefix each field name with this for output
        writers:
          - class: TextFileWriter
          - class: CachedDataWriter
            kwargs:
              data_server: <<data_server>>


###########################################################
loggers:
  PCOD:
    logger_template: text_file_logger_template
  cwnc:
    logger_template: text_file_logger_template
  gp02:
    logger_template: text_file_logger_template
  gyr1:
    logger_template: text_file_logger_template
  adcp:
    logger_template: text_file_logger_template
  eng1:
    logger_template: text_file_logger_template
  svp1:
    logger_template: text_file_logger_template
  twnc:
    logger_template: text_file_logger_template
  mbdp:
    logger_template: text_file_logger_template
  knud:
    logger_template: text_file_logger_template
  grv1:
    logger_template: text_file_logger_template
  mwx1:
    logger_template: text_file_logger_template
  pco2:
    logger_template: text_file_logger_template
  pguv:
    logger_template: text_file_logger_template
  s330:
    logger_template: text_file_logger_template
  tsg1:
    logger_template: text_file_logger_template
  rtmp:
    logger_template: text_file_logger_template
  hdas:
    logger_template: text_file_logger_template
  tsg2:
    logger_template: text_file_logger_template
  seap:
    logger_template: text_file_logger_template

  # Read a bunch of variables from CDS, compute 30-second snapshot and write back
  # to CDS and optionally InfluxDB. This *totally* needs a way to be generalized!!!
  rebuild_snapshot:
    logger_template: rebuild_snapshot_template
    variables:
      snapshot_fields: [ KnudDepthHF, KnudDepthLF]
      interval: 5
      window: 5

###########################################################
modes:
  'off':  # without a 'default_mode' key, first defined mode will be default
    [PCOD-off, cwnc-off, gp02-off, gyr1-off, adcp-off, eng1-off, svp1-off, twnc-off, mbdp-off, knud-off, grv1-off, mwx1-off, pco2-off, pguv-off, s330-off, tsg1-off, rtmp-off, hdas-off, tsg2-off, seap-off, rebuild_snapshot-off]

  'on':
    [PCOD-net, cwnc-net, gp02-net, gyr1-net, adcp-net, eng1-net, svp1-net, twnc-net, mbdp-net, knud-net, grv1-net, mwx1-net, pco2-net, pguv-net, s330-net, tsg1-net, rtmp-net, hdas-net, tsg2-net, seap-net, rebuild_snapshot-on]
```
